spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://host.docker.internal/
    username: postgres
    password: postgres
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/game
      database: game

security:
  jwt:
    token:
      secret: secret